# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'semestralka' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  # Pods for semestralka
  pod 'FontAwesome.swift'

  target 'semestralkaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'semestralkaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
